# Install services on webserver
---
- name: Install mysql server 8 and initialize
  hosts: azurevms
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: Th1sIsAP@ssw0rd
    user: crhis
    password: admin
    dbname: parcialappdb
  tasks:
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started

    - name: "Create user {{ user }}"
      mysql_user:
        name: "{{ user }}"
        password: "{{ password }}"
        check_implicit_admin: yes
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        state: present
        host: "%"

    - name: Ensure root user can only login from localhost
      mysql_user:
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        state: present
      with_items:
        - localhost
        - 127.0.0.1
        - ::1

    - name: create a new database
      mysql_db: name=testdb state=present login_user=root login_password="{{ mysql_root_password }}"

    - name: add sample data to database
      copy:
        src: dump.sql
        dest: /tmp/dump.sql

    - name: insert sample data into database
      mysql_db: name={{ dbname }} state=import target=/tmp/dump.sql login_user=root login_password="{{ mysql_root_password }}"

    - name: Add .my.cnf to user home
      template:
        src: my.cnf.j2
        dest: /root/.my.cnf

    - name: Reload privilege tables
      command: |
        mysql -p{{ mysql_root_password }} -ne "{{ item }}"
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False

    - name: Remove anonymous users
      command: |
        mysql -p{{ mysql_root_password }} -ne "{{ item }}"
      with_items:
        - DELETE FROM mysql.user WHERE User=''
      changed_when: False

    - name: Disallow root login remotely
      command: |
        mysql -p{{ mysql_root_password }} -ne "{{ item }}"
      with_items:
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      changed_when: False

    - name: Remove test database and access to it
      command: |
        mysql -p{{ mysql_root_password }} -ne "{{ item }}"
      with_items:
        - DROP DATABASE IF EXISTS test
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
      changed_when: False

    - name: Reload privilege tables
      command: |
        mysql -p{{ mysql_root_password }} -ne "{{ item }}"
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False

    - name: Delete .my.conf
      file:
        path: /root/.my.cnf
        state: absent
    - name: Modify configuration file to listen on all interfaces
      lineinfile: dest=/etc/my.cnf.d/mariadb-server.cnf regexp="^bind-address" line="bind-address=0.0.0.0"
